### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by NandiyaLive** [gdgsrilanka/google-io-2024-web#1]
- Design a hero section similar to :  https://io.google/2024
- Change heading, sub heading
- Add a Register button

![image](https://github.com/gdgsrilanka/google-io-2024-web/assets/30690726/881c0676-2a21-4260-9f3e-7e6825a2054d)

**Comment by donheshanthaka** [comment]
Hey team, I would like to work on this issue.

Question: Can we use the same image from the main event?

**Comment by chamodshehanka** [comment]
> Hey team, I would like to work on this issue.
> 
> Question: Can we use the same image from the main event?

of course, or else you can use brand assets from here https://docs.google.com/presentation/d/1ta4cJ2bzYTCTsfhnzmdIfJhPBe7Vm27EHWkeEmlu7Rw/edit?resourcekey=0-RDQfb7Eh8mc8TBgC-Pm4-g#slide=id.g26eb9b5c40d_0_0

**Comment by donheshanthaka** [comment]
@chamodshehanka are we sticking to the dark theme that is default on the main website or developing a switchable app?

**Comment by chamodshehanka** [comment]
> @chamodshehanka are we sticking to the dark theme that is default on the main website or developing a switchable app?

let's stick to dark mode for now

**Comment by chamodshehanka** [comment]
@donheshanthaka next time don't close issues without getting merge PRs

**Comment by donheshanthaka** [comment]
Yeah my bad, I didn't knew it would close the issue after moving it to done before getting the PR merged. Won't happen next time.
